on:
  push:
    branches:
      - master
      - develop
      - "feature/**"
      - "release/**"
      - "hotfix/**"
    tags:
      - "*.*.*"
    paths-ignore:
      - "README.md"

  pull_request:

  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        job:
          - os: windows-2019
            build: ./build.cmd
            push: true
          - os: windows-2022
            build: ./build.cmd
    name: ${{ matrix.job.os }}
    runs-on: ${{ matrix.job.os }}
    steps:
      - name: Setup netcoreapp3.1
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: "3.1.415"
      - name: Setup net5.0
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: "5.0.403"
      - name: Setup net6.0
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: "6.0.100"
      - name: Run dotnet --info
        run: dotnet --info
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Build
        run: ${{ matrix.job.build }} --verbosity=diagnostic --target=pack
      - name: Publish artifacts
        if: matrix.job.push && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
        uses: actions/upload-artifact@v2.3.1
        with:
          if-no-files-found: warn
          name: package
          path: artifact/nuget/**/*
